# enable traefik SSL termination

# without this config, only perform routing
# upstream infra apache terminates ssl (wildcard cert via puppet)
---
version: "3.7"
services:
  ingress:
    command:
      #- "--log.level=DEBUG"

      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=ingress-network"

      # required for Let's Encrypt http challenge
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # redirect http to https
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"

      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"

      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      # Let's Encrypt challenges
      - "80:80"
      # web UI
      - "8080:8080"
      # https
      - "443:443"

  dashboard:
    labels:
      traefik.http.routers.dashboard.entrypoints: websecure
  
  keycloak:
    labels:
      traefik.http.routers.keycloak.entrypoints: websecure
  
  fhir:
    labels:
      traefik.http.routers.fhir.entrypoints: websecure
