version: "3.7"
services:
  dashboard:
    env_file:
      - ../../../dev/freestanding/femr/dashboard.env


  keycloak:
    env_file:
      - ../../../dev/freestanding/femr/keycloak.env


  fhirwall:
    env_file:
      - ../../../dev/freestanding/femr/fhirwall.env


  fhirwall:
    env_file:
      - ../../../dev/freestanding/femr/fhirwall.env


  pdmp:
    env_file:
      - ../../../dev/freestanding/femr/pdmp.env
    volumes:
      - ../../../dev/freestanding/femr/config/pdmp/:/opt/app/config:ro


  hydrant:
    env_file:
      - ../../../dev/freestanding/femr/hydrant.env
