srs.ncpdp2017.senderSoftwareVersion=3.1
srs.ncpdp2017.prescriber.firstName=N/A
srs.ncpdp2017.prescriber.lastName=N/A
srs.ncpdp2017.pharmacy.npi=N/A
srs.ncpdp2017.pharmacy.ncpdp=N/A
srs.ncpdp2017.pdmpstaterespondeddeferred= error
srs.ncpdp2017.pdmpstaterespondednotfound= error
srs.ncpdp2017.pdmpstaterespondederror= error
srs.ncpdp2017.pdmpstaterespondeddisallowed= error
srs.ncpdp2017.http.error=200
#srs.ncpdp2017.patient.dob = 1900-01-01
#srs.ncpdp2017.medicationDispensed.lastFillDate = 1900-01-01
srs.ncpdp2017.medicationDispensed.drugDescription = N/A
srs.ncpdp2017.medicationDispensed.quantity.value = 0
srs.ncpdp2017.medicationDispensed.historySource.paymentType = 99
srs.ncpdp2017.patient.telePhone=0
srs.ncpdp2017.pharmacy.businessName = N/A