version: "3.7"
services:
  dashboard:
    image: ghcr.io/uwcirg/cosri-patientsearch:${DASHBOARD_IMAGE_TAG:-develop}
    environment:
      OIDC_AUTHORIZE_URL: "https://keycloak.${BASE_DOMAIN:-localtest.me}/auth/realms/fEMR/protocol/openid-connect/auth"
      OIDC_CLIENT_ID: femr_openid_client
      OIDC_ISSUER: "https://keycloak.${BASE_DOMAIN:-localtest.me}/auth/realms/fEMR"
      OIDC_REDIRECT_URIS: "https://keycloak.${BASE_DOMAIN:-localtest.me}/oidc_callback"
      OIDC_USERINFO_URI: "https://keycloak.${BASE_DOMAIN:-localtest.me}/auth/realms/fEMR/protocol/openid-connect/userinfo"
      OIDC_TOKEN_URI: "https://keycloak.${BASE_DOMAIN:-localtest.me}/auth/realms/fEMR/protocol/openid-connect/token"
      OIDC_TOKEN_INTROSPECTION_URI: "https://keycloak.${BASE_DOMAIN:-localtest.me}/auth/realms/fEMR/protocol/openid-connect/token/introspect"
      EXTERNAL_FHIR_API: 'http://pdmp-internal:8008/v/r2/fhir/'
      # FHIR URL queried by PDMP integration backend
      MAP_API: "http://fhir-internal:8080/fhir/"
      # fhir-migrations run against FHIR_URL
      FHIR_URL: "http://fhir-internal:8080/fhir/"
      MIGRATION_SCRIPTS_DIR: /opt/migrations
      # FHIR URL passed to SoF client
      SOF_HOST_FHIR_URL: 'https://fhirwall.${BASE_DOMAIN:-localtest.me}/fhir'
      SOF_CLIENT_LAUNCH_URL: 'https://backend.${BASE_DOMAIN:-localtest.me}/auth/launch'
      SOF_CLIENTS: '[{"id":"COSRI", "label":"View", "launch_url":"https://backend.${BASE_DOMAIN}/auth/launch"}]'
      LOGSERVER_URL: "https://logs.${BASE_DOMAIN:-localtest.me}"
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - keycloak
      - pdmp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard-${COMPOSE_PROJECT_NAME}.rule=Host(`dashboard.${BASE_DOMAIN:-localtest.me}`)"
      - "traefik.http.routers.dashboard-${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.dashboard-${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.dashboard-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt"
    networks:
      - ingress
      - internal
    volumes:
      - ./config/migrations:/opt/migrations


  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_IMAGE_TAG:-15.0.2}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak-${COMPOSE_PROJECT_NAME}.rule=Host(`keycloak.${BASE_DOMAIN:-localtest.me}`)"
      - "traefik.http.routers.keycloak-${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.keycloak-${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.keycloak-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt"
    entrypoint:
      # override default keycloak docker entrypoint script with our own
      - /opt/jboss/tools/docker-entrypoint-override.sh
      - /opt/jboss/tools/docker-entrypoint.sh
    command:
      - "-b"
      - "0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      # TODO use dir migration provider (`keycloak.migration.provider=dir`)
      # https://github.com/keycloak/keycloak-documentation/blob/master/server_admin/topics/export-import.adoc
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
      - "-Dkeycloak.migration.file=/opt/jboss/keycloak/realm-data.json"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    environment:
      KEYCLOAK_FRONTEND_URL: "https://keycloak.${BASE_DOMAIN:-localtest.me}/auth"
      PROXY_ADDRESS_FORWARDING: "true"
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
      # https://nvd.nist.gov/vuln/detail/CVE-2021-44228
      LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"

      # environment variables used to configure docker-entrypoint-override.sh
      __KEYCLOAK_INPUT_CONFIG: /tmp/realm-data.json
      __KEYCLOAK_OUTPUT_CONFIG: /opt/jboss/keycloak/realm-data.json
    volumes:
      - "./config/keycloak/docker-entrypoint-override.sh:/opt/jboss/tools/docker-entrypoint-override.sh:ro"
      - "./config/keycloak/realm-data.json:/tmp/realm-data.json"
      - "./config/keycloak/cosri-keycloak-theme:/opt/jboss/keycloak/themes/cosri"
      - "./config/keycloak/jboss-logging-config.cli:/opt/jboss/startup-scripts/jboss-logging-config.cli"
    depends_on:
      - db
    networks:
      - ingress
      - internal


  fhir:
    image: hapiproject/hapi:${FHIR_IMAGE_TAG:-v6.2.2}
    environment:
      SPRING_CONFIG_LOCATION: file:///opt/application.yaml
      spring.datasource.url: jdbc:postgresql://db:5432/hapifhir
      spring.datasource.username: postgres
      spring.datasource.password: postgres
      spring.datasource.driverClassName: org.postgresql.Driver
      spring.jpa.properties.hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect

      # make URLs relative to dashboard to allow pagination
      # TODO remove when dashboard is able to rewrite URLs
      hapi.fhir.server_address: 'https://dashboard.${BASE_DOMAIN:-localtest.me}/fhir/'

      # https://nvd.nist.gov/vuln/detail/CVE-2021-44228
      LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"

    volumes:
      - "./config/fhir/application.yaml:/opt/application.yaml:ro"
    depends_on:
      - db
    networks:
      internal:
        aliases:
          - fhir-internal


  fhirwall:
    image: ghcr.io/uwcirg/jwt-proxy:${PROXY_IMAGE_TAG:-latest}
    environment:
      UPSTREAM_SERVER: "http://fhir-internal:8080"
      JWKS_URL: "https://keycloak.${BASE_DOMAIN:-localtest.me}/auth/realms/fEMR/protocol/openid-connect/certs"
      PATH_WHITELIST: /fhir/metadata
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fhirwall-${COMPOSE_PROJECT_NAME}.rule=Host(`fhirwall.${BASE_DOMAIN:-localtest.me}`)"
      - "traefik.http.routers.fhirwall-${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.fhirwall-${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.fhirwall-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt"
    networks:
      - ingress
      - internal


  pdmp:
    image: ghcr.io/uwcirg/script-fhir-facade:${PDMP_IMAGE_TAG:-develop}
    environment:
      RXNAV_LOOKUP_ENABLED: "true"
      REQUEST_CACHE_URL: redis://redis:6379/0
    volumes:
      - ./config/pdmp:/opt/app/config:ro
    networks:
      internal:
        aliases:
          - pdmp-internal
    depends_on:
      - redis


  hydrant:
    image: ghcr.io/uwcirg/hydrant:${HYDRANT_IMAGE_TAG:-develop}
    environment:
      PREFERRED_URL_SCHEME: https
      FHIR_SERVER_URL: "http://fhir-internal:8080/fhir"
      LOGSERVER_URL: "https://logs.${BASE_DOMAIN:-localtest.me}"

      # Keycloak database config
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db
    networks:
      - internal


  redis:
    image: redis
    networks:
      - internal

  db:
    image: postgres:${POSTGRES_IMAGE_TAG:-17}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "db-data:/var/lib/postgresql/data"
      # create keycloak and HAPI application databases
      - "./config/db:/docker-entrypoint-initdb.d"
    networks:
      - internal

volumes:
  db-data:

networks:
  # internal network for backing services
  internal:

  # ingress network
  ingress:
    external: true
    name: external_web
