version: "3.7"
services:
  frontend:
    build:
      context: https://github.com/uwcirg/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY.git
      dockerfile: Dockerfile.production

    environment:
      # confidential backend API endpoint
      # NB: domain is required for cookies to be set
      REACT_APP_CONF_API_URL: "https://backend.${BASE_DOMAIN:-localtest.me}"

      
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.frontend.rule=Host(`frontend.${BASE_DOMAIN:-localtest.me}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
    networks:
     - ingress-network

  backend:
    image: "uwcirg/sof-api-wrapper:develop"

    environment:
      SECRET_KEY: qiLYeYMJf8i7y0xU

      # client ID registered with SoF host (Keycloak)
      SOF_CLIENT_ID: fe6ccba2-7bef-47db-8ca7-32b916dcdd8a
      SOF_CLIENT_SECRET: a92b4f24-82cb-4b04-baee-b933f55e2039

      PREFERRED_URL_SCHEME: https
      # ultimate destination after SoF launch and backend auth
      LAUNCH_DEST: 'https://frontend.${BASE_DOMAIN:-localtest.me}/launch.html'

      # do not pass launch/patient or Epic will infer standalone launch
      SOF_CLIENT_SCOPES: "patient/*.read launch openid profile"
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.backend.rule=Host(`backend.${BASE_DOMAIN:-localtest.me}`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
    networks:
     - ingress-network

networks:
  ingress-network:
    # override COMPOSE_PROJECT_NAME namespacing; use exact network name
    name: ingress-network
