version: "3.7"
services:
  frontend:
    build:
      context: https://github.com/uwcirg/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY.git
      dockerfile: Dockerfile.production

    volumes:
      - ./:/opt/app
    #env_file:
      # Reuse .env from CRA
      #- .env
    labels:
      - "traefik.enable=true"

      #- "traefik.http.routers.frontend.rule=Host(`frontend.${BASE_DOMAIN:-localtest.me}`)"
      #- "traefik.http.routers.frontend.entrypoints=web"

      - "traefik.http.routers.frontend.rule=Host(`frontend.${BASE_DOMAIN:-localtest.me}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
    networks:
     - ingress-network

  backend:
    build:
      context: https://github.com/uwcirg/sof-api-wrapper.git
    volumes:
      - ./:/opt/app
      # mount host certificate bundle into container
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      # mount host hosts file into container
      - /etc/hosts:/etc/hosts:ro

    environment:
      REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
    #env_file:
      #- sof_wrapper.env
    labels:
      - "traefik.enable=true"

      #- "traefik.http.routers.backend.rule=Host(`backend.${BASE_DOMAIN:-localtest.me}`)"
      #- "traefik.http.routers.backend.entrypoints=web"

      - "traefik.http.routers.backend.rule=Host(`backend.${BASE_DOMAIN:-localtest.me}`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
    networks:
     - ingress-network

networks:
  ingress-network:
    # override COMPOSE_PROJECT_NAME namespacing; use exact network name
    name: ingress-network
