# enable traefik SSL termination

# without this config, only perform routing
# upstream infra apache terminates ssl (wildcard cert via puppet)
---
version: "3.7"
services:
  frontend:
    labels:
      traefik.http.routers.frontend.entrypoints: websecure
  backend:
    labels:
      traefik.http.routers.backend.entrypoints: websecure
