# docker-compose override to disable theme caching
version: "3.7"
services:
  keycloak:
    volumes:
      - "../../../dev/freestanding/femr/config/keycloak/disable-theme-cache.cli:/opt/jboss/startup-scripts/disable-theme-cache.cli"
