# docker-compose development override for fhirwall service
version: "3.7"
services:
  fhirwall:
    command: sh -c "flask run --host 0.0.0.0 --port ${PORT:-8000}"
    environment:
      FLASK_ENV: development
    volumes:
    # set in .env
      - '${FHIRWALL_CHECKOUT_DIR}/:/opt/app'
