version: "3.7"
services:
  frontend:
    image: uwcirg/cosri-summary
    environment:
      # confidential backend API endpoint
      # NB: domain is required for cookies to be set
      REACT_APP_CONF_API_URL: "https://backend.${BASE_DOMAIN:-localtest.me}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-${COMPOSE_PROJECT_NAME}.rule=Host(`frontend.${BASE_DOMAIN:-localtest.me}`)"
      - "traefik.http.routers.frontend-${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.frontend-${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.frontend-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt"
    networks:
      - ingress

  backend:
    image: "uwcirg/sof-api-wrapper:develop"
    environment:
      SECRET_KEY: ${SECRET_KEY:-qiLYeYMJf8i7y0xU}

      # client ID registered with SoF host
      SOF_CLIENT_ID: ${SOF_CLIENT_ID:-cosri_openid_client}
      SOF_CLIENT_SECRET: ${SOF_CLIENT_SECRET:-cosri_openid_client_secret}

      PREFERRED_URL_SCHEME: https
      # ultimate destination after SoF launch and backend auth
      LAUNCH_DEST: 'https://frontend.${BASE_DOMAIN:-localtest.me}/launch.html'

      PDMP_URL: 'https://pdmp.${BASE_DOMAIN:-localtest.me}'

      # do not pass launch/patient or Epic will infer standalone launch
      SOF_CLIENT_SCOPES: ${SOF_CLIENT_SCOPES:-patient/*.read launch openid profile}

      SESSION_REDIS: redis://redis:6379/0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-${COMPOSE_PROJECT_NAME}.rule=Host(`backend.${BASE_DOMAIN:-localtest.me}`)"
      - "traefik.http.routers.backend-${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.backend-${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.backend-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt"
    networks:
      - ingress
      - internal
    depends_on:
      - redis

  redis:
    image: redis
    networks:
      - internal

networks:
  # internal network for backing services
  internal:

  # ingress network
  ingress:
    external: true
    name: external_web
