version: "3.7"
services:
  frontend:
    restart: unless-stopped
    env_file:
      - ../../../dev/freestanding/cosri/frontend.env


  backend:
    restart: unless-stopped
    env_file:
      - ../../../dev/freestanding/cosri/backend.env


  pdmp:
    restart: unless-stopped
    env_file:
      - ../../../dev/freestanding/cosri/pdmp.env
    volumes:
      - ../../../dev/freestanding/cosri/config/pdmp/:/opt/app/config:ro

  redis:
    restart: unless-stopped
