# docker-compose development override for backend service
version: "3.7"
services:
  backend:
    command: sh -c "flask run --host 0.0.0.0 --port ${PORT:-8000}"
    environment:
      FLASK_ENV: development
    volumes:
    # set in .env
      - '${BACKEND_CHECKOUT_DIR}/:/opt/app'
