version: "3.7"
services:
  frontend:
    environment:
      REACT_APP_SYSTEM_TYPE: development
    env_file:
      - ../../../dev/freestanding/cosri/frontend.env


  backend:
    environment:
      DEBUG_OUTPUT_DIR: /var/local/backend-output
    env_file:
      - ../../../dev/freestanding/cosri/backend.env
    volumes:
      - ../../../dev/freestanding/cosri/backend-output/:/var/local/backend-output


  pdmp:
    env_file:
      - ../../../dev/freestanding/cosri/pdmp.env
    volumes:
      - ../../../dev/freestanding/cosri/config/pdmp/:/opt/app/config:ro
