---
version: "3.7"
services:
  frontend:
    env_file:
      - ../../../dev/ehr-embedded/cosri/frontend.env


  backend:
    environment:
      DEBUG_OUTPUT_DIR: /var/local/backend-output
    env_file:
      - ../../../dev/ehr-embedded/cosri/backend.env
    volumes:
      - ../../../dev/ehr-embedded/cosri/backend-output/:/var/local/backend-output


  pdmp:
    environment:
      SCRIPT_MOCK_URL: https://github.com/uwcirg/pdmp-mock-data
    env_file:
      - ../../../dev/ehr-embedded/cosri/pdmp.env
    volumes:
      - ../../../dev/ehr-embedded/cosri/config/pdmp/:/opt/app/config:ro
